sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

script:
  - sh bin/install-dependencies.sh && sh bin/test.sh

deploy:
  provider: script
  script: sh bin/build-image.sh
  on:
    branch: master

notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=0abbabd2860ac8a508729e1422281703d41ac9bf55919519688ba1cbe03f50ea
